[workspace]
members = [
  "librubyfmt",
]

[package]
name = "rubyfmt-main"
version = "0.14.1"
authors = ["Fable Tales <penelopedotzone@gmail.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
ctrlc = { version = "3.2", features = ["termination"] }
ignore = "0.4.18"
regex = "1.11.1"
rubyfmt = { path = "./librubyfmt" }
similar = { version = "2.7.0", features = ["bytes"] }

[dev-dependencies]
assert_cmd = "2"
tempfile = "3.19"
libtest-mimic = "0.8.1"
criterion = { version = "0.8", features = ["html_reports"] }

[[test]]
name = "fixtures_test"
path = "tests/fixtures_test.rs"
harness = false

[[bench]]
name = "formatting"
harness = false

[profile.release]
debug = true