#!/bin/bash
set -euxo pipefail

while IFS= read -r -d '' FN
do
    if echo "$FN" | grep -v 'rspec'
    then
        ruby --disable=gems test.rb "$FN"
    fi
done <   <(find ../fixtures -type f -print0 -not -name "*2.6*")
