[package]
name = "rubyfmt"
version = "0.14.1"
authors = ["Fable Tales <penelopedotzone@gmail.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4.8", features = ["max_level_debug", "release_max_level_warn"] }
memchr = "2.7"
simplelog = "0.12"
ruby-prism="1.9.0"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { version = "0.6.1", features = ["disable_initial_exec_tls"], optional=true }

[lib]
name = "rubyfmt"
crate-type = ["staticlib", "rlib"]

[features]
default = ["use_jemalloc"]
use_jemalloc = ["tikv-jemallocator"]
