name: Benchmark

on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true

      - uses: actions-rust-lang/setup-rust-toolchain@ecabd13d1c56bd1345c230e542e9144811ad706f # v2.0.0
        with:
          toolchain: 1.99.0
          override: true
          cache: true

      - name: Build release binary
        run: cargo build --release

      - name: Run benchmarks
        run: cargo bench

      - name: Generate benchmark summary
        run: ./script/format_bench_summary
