name: CI
on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

env:
    BUNDLE_PATH: /tmp/.bundle
    GEM_HOME: /tmp/.bundle
    GEM_PATH: /tmp/.bundle
    TERM: xterm256
    SCCACHE_DIR: /tmp/sccache
    RUSTC_WRAPPER: sccache

jobs:
  CI:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow-failure }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        allow-failure: [false]
        include:
          - os: windows-latest
            allow-failure: true
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-2-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/cache@v2
      with:
        path: |
          /tmp/sccache
        key: ${{ runner.os }}-sccache-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/cache@v2
      with:
        path: |
          librubyfmt/ruby_checkout
        key: ${{ runner.os }}-ruby-v1-${{ hashFiles('.git/modules/librubyfmt/ruby_checkout/HEAD') }}
    - if: runner.os == 'Linux'
      run: |
        sudo apt-get install -y shellcheck build-essential ruby-dev bison

        SCCACHE_VERSION=0.2.15
        SCCACHE_FILE=sccache-v$SCCACHE_VERSION-x86_64-unknown-linux-musl
        mkdir -p $HOME/.local/bin
        curl -L "https://github.com/mozilla/sccache/releases/download/v$SCCACHE_VERSION/$SCCACHE_FILE.tar.gz" | tar xz
        chmod +x $SCCACHE_FILE/sccache
        mv -f $SCCACHE_FILE/sccache $HOME/.local/bin/sccache
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - if: runner.os == 'macOS'
      run: |
        rustup component add clippy --toolchain stable-x86_64-apple-darwin
        rustup component add rustfmt --toolchain stable-x86_64-apple-darwin
        brew install shellcheck sccache automake
    - if: runner.os == 'Windows'
      run: |
        choco install sccache
    - run: ./script/ci
      shell: 'bash'
