name: CI
on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

env:
    BUNDLE_PATH: /tmp/.bundle
    GEM_HOME: /tmp/.bundle
    GEM_PATH: /tmp/.bundle
    TERM: xterm256

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          override: true
          profile: minimal
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.63.0
          components: clippy
          override: true
          profile: minimal
      - run: cargo clippy --all --all-features -- -D warnings

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          sudo apt-get install -y shellcheck
          ./script/lints/lint_fixtures.sh
          ./script/lints/lint_scripts.sh

  cross_compile:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.63.0
          override: true
          profile: minimal
          target: aarch64-unknown-linux-gnu
      - run: |
          wget https://github.com/postmodern/ruby-install/releases/download/v0.9.0/ruby-install-0.9.0.tar.gz
          tar -xzvf ruby-install-0.9.0.tar.gz
          cd ruby-install-0.9.0/
          sudo make install
          cd ..
          ruby-install ruby 2.7.1 -c -- --with-arch=arm64 CFLAGS=-DUSE_FFI_CLOSURE_ALLOC=1

          export CC_aarch64_unknown_linux_gnu=clang
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: aarch64-unknown-linux-gnu
          args: "--release"
          strip: true
      - uses: actions/upload-artifact@v3
        with:
          name: rubyfmt-artifact-ubuntu-20.04-aarch64
          path: target/release/rubyfmt-main

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, macos-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.63.0
        override: true
        profile: minimal
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-2-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/cache@v2
      with:
        path: |
          librubyfmt/ruby_checkout
        key: ${{ runner.os }}-ruby-v1-${{ hashFiles('.git/modules/librubyfmt/ruby_checkout/HEAD') }}
    - if: runner.os == 'macOS'
      run: |
        brew install automake bison
        echo "/usr/local/opt/bison/bin:$PATH" >> $GITHUB_PATH
    - run: ./script/test.sh
    - uses: actions/upload-artifact@v3
      with:
        name: rubyfmt-artifact-${{ matrix.os }}
        path: target/release/rubyfmt-main

