name: CI
on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

env:
    BUNDLE_PATH: /tmp/.bundle
    GEM_HOME: /tmp/.bundle
    GEM_PATH: /tmp/.bundle
    TERM: xterm256

jobs:
  CI:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - run: |
        git submodule init
        git submodule update
    - if: runner.os == 'Linux'
      run: |
        sudo apt-get install -y shellcheck build-essential ruby-dev bison
    - if: runner.os == 'macOS'
      run: |
        rustup component add clippy --toolchain stable-x86_64-apple-darwin
        rustup component add rustfmt --toolchain stable-x86_64-apple-darwin
        brew install shellcheck automake
    - run: ./script/ci
